version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: upgradeperu_web:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio.rule=Host(`upgradeperu.protocolo2r.store`)"
      - "traefik.http.routers.portfolio.entrypoints=websecure"
      - "traefik.http.routers.portfolio.tls.certresolver=myresolver"

networks:
  traefik_proxy:
    external: true
